language: php

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: bionic
    - php: 7.2
      dist: bionic
    - php: 7.3
      dist: bionic
    - php: 7.4
      dist: bionic

services:
  - mysql

sudo: false

before_script:
  - mysql -e "create database IF NOT EXISTS omeka_test;" -uroot
  - mv application/config/config.ini.changeme application/config/config.ini
  - mv application/tests/config.ini.changeme application/tests/config.ini
  - sed -i 's/db.host = ""/db.host = "localhost"/' application/tests/config.ini
  - sed -i 's/db.username = ""/db.username = "root"/' application/tests/config.ini
  - sed -i 's/db.dbname = ""/db.dbname = "omeka_test"/' application/tests/config.ini
  - sed -i 's/paths.imagemagick = ""/paths.imagemagick = "\/usr\/bin\/"/' application/tests/config.ini

script:
  - composer install
  - cd application/tests && ../../vendor/bin/phpunit
